id: P000212
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །ཐེག་པ་མཆོག་གི་རྣལ་འབྱོར་པ་བྱ་བྲལ་ཀུན་དགའ་དཔལ་ལྡན་གྱི་རྣམ་ཐར་ངོ་མཚར་བདུད་རྩིའི་སྣང་བ་བཞུགས་སོ།
    །
  authors:
  - མཛད་པ་པོ། ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  layers:
  - book_title
  - author
  id: SHE-DKR-05
web_metadata:
  title:
    en: Amazing Lights of Nectar:A Biography of Khenpo Kunzang Palden
    bo: ཐེག་པ་མཆོག་གི་རྣལ་འབྱོར་པ་བྱ་བྲལ་ཀུན་དགའ་དཔལ་ལྡན་གྱི་རྣམ་ཐར་ངོ་མཚར་བདུད་རྩིའི་སྣང་བ་བཞུགས་སོ།
  collection:
    en: Dilgo Khyentse Series–  Book 5
    bo: དིལ་མགོ་མཁྱེན་བཙེ་གསུང་འབུམ།–  དེབ། ༥
  author:
    en: Kyabje Dilgo Khyentse Rinpoche
    bo: ༧སྐྱབས་རྗེ་དིལ་མགོ་མཁྱེན་བཙེ་རིན་པོ་ཆེ།
  pusblisher:
    en: Shechen Publications
    bo: ཞེ་ཆེན་བསྟན་གཉིས་དར་རྒྱས་གླིང།
  sku: SHE-DKR-05
  category:
    en: Biography
    bo: རྣམ་ཐར།
  org:
    bo: Timeless Treasuries
    en: མཐའ་ཡས་དཔེ་མཛོད།
  website: http://dharmacloud.tsadra.org
  aquisition_data: '2019-07-18'
  filename: SHE-DKR-05.epub
  description:
    en: ''
    bo: ''
